// NJ MVC Basic Driver Examination – All 4 Exams (50 questions each)
// options: array of 4 strings [A, B, C, D]
// correct: 0=A, 1=B, 2=C, 3=D

const EXAMS = [
  {
    id: 1,
    title: "Exam #1",
    questions: [
      { q: "When 2 roads intersect and there are no signs or signals, it is a good practice to:", o: ["blow your horn as a warning","be ready to stop if necessary","pull to the right hand lane and stop","always yield to traffic on the left"], a: 1 },
      { q: "You may not park within how many feet of a fire hydrant?", o: ["10 feet","50 feet","25 feet","20 feet"], a: 0 },
      { q: "When making a left turn from a two-way road onto a 4 lane highway, the proper way to turn is:", o: ["approach the turn as close to the centerline of the road as possible","make the turn before reaching the center of the intersection","turn into the left lane of the road going in your direction","all of the above"], a: 3 },
      { q: "When approaching or nearing an uncontrolled intersection you should:", o: ["always come to a full stop","slow down and look straight ahead","speed up to clear intersection quickly","reduce speed and be ready to stop"], a: 3 },
      { q: "Dim your lights to low beam when:", o: ["a car is approaching you or when you are behind another car","parking on an unlit highway","entering a curve","driving on dark roads"], a: 0 },
      { q: "On a two-lane road, not near a school, when a school bus is stopped and its red lights are flashing:", o: ["you must stop","you may pass the bus from either direction","you may pass the bus at a speed of 10 m.p.h. or less","you may pass the bus with caution"], a: 0 },
      { q: "In the event of a crash or sudden stop, use of seat belts may:", o: ["keep you from being thrown from the car","keep you from hitting the windshield or dashboard","keep you from sliding off the seat and losing control of the car","all of the above"], a: 3 },
      { q: "Driving while under the influence of intoxicating beverages means:", o: ["your senses or judgment are impaired by alcohol","drinking while in process of driving the vehicle","the driver shows obvious signs of being drunk","driving even if the driver has had one drink"], a: 0 },
      { q: "Studies show that the greatest number of people arrested for drunk driving have been drinking:", o: ["beer","whiskey","wine","mixed drinks"], a: 0 },
      { q: "To safely share the road with large trucks and buses, you must know:", o: ["The impact trucks and large vehicles have on the environment.","The horsepower rating of your vehicle.","Limitations of these vehicles regarding visibility, stopping distances required and maneuverability.","The history of the trucking industry."], a: 2 },
      { q: "You can reduce your chances of being involved in an accident by knowing and using the standard accident prevention formula:", o: ["be alert","be prepared","act in time","all of the above"], a: 3 },
      { q: "If a vehicle is passing you, you should", o: ["slow down to make it easier for the driver to complete the pass in time","flash your lights and sound your horn to warn the car passing that it is unsafe","continue at the same speed and signal oncoming traffic","speed up so he will not complete the pass"], a: 0 },
      { q: "If you approach an intersection and a large truck is stopped for the traffic light, you should:", o: ["Stop as close to the rear of the truck as possible so no one can get in front of you.","Go around the truck on the right because he will start up slower.","Blow your horn so the driver will know you are there.","Stop with enough distance so you will not be in a blind spot and you can see the driver in his mirror."], a: 3 },
      { q: "If you are under 21 years of age and drive a vehicle with as little as 0.01% blood alcohol concentration, you are subject to a penalty of:", o: ["30 to 90 day driver license suspension.","15 to 30 days community service.","participation in an intoxicated driver resource center or other alcohol education highway safety program.","all of the above."], a: 3 },
      { q: "In New Jersey, studded snow tires can be legally used between:", o: ["April 1st and December 15th","September 30th and May 30th","November 15th and April 1st","October 15th and March 15th"], a: 2 },
      { q: "The best way to reduce your chances of having an alcohol related accident is to:", o: ["reduce your drinking","have a meal before drinking","not drive at all after drinking","know your own limits"], a: 2 },
      { q: "The meaning of a hand-signal when a driver's hand and arm are upward is:", o: ["U-Turn","Slow-Stop","Left-Turn","Right-Turn"], a: 3 },
      { q: "The best way to take a curve is:", o: ["slow down before entering the curve","speed up while in the curve","lean in the direction of the curve","slow down after entering the curve"], a: 0 },
      { q: "Who is required by the GDL law to wear a seat belt in the vehicle?", o: ["The driver and all passengers","The driver and front seat passenger","The driver and supervising driver","The driver"], a: 0 },
      { q: "Road surfaces are most slippery:", o: ["during very hot, humid weather","during the first few minutes of a rainfall","after a very heavy rainfall","during very cold, dry weather"], a: 1 },
      { q: "You should always yield to:", o: ["emergency vehicles","pedestrians","other vehicles already in the intersection","all of the above"], a: 3 },
      { q: "Altering a driver's license, or showing an altered driver's license, may result in", o: ["a fine of up to $1,000","up to 6 months imprisonment","loss of your driving privilege","all of the above"], a: 3 },
      { q: "Which of the following drinks contain the highest alcohol content?", o: ["5 ounces of table wine","1½ ounces of whiskey","12 ounces of beer","all of the above are about equal in content"], a: 3 },
      { q: "In adverse weather conditions, a truck takes longer to stop. This can be as much as:", o: ["100% more","50% more","25% more","70% more"], a: 2 },
      { q: "The New Jersey speed limit in a business or residential area, unless otherwise posted, is:", o: ["30 m.p.h.","25 m.p.h.","20 m.p.h.","35 m.p.h."], a: 1 },
      { q: "To regain control while in a skid, you should:", o: ["keep a tight grip on the steering wheel","turn in the same direction the back of the car is skidding","turn in the opposite direction the back of the car is skidding","make a fast turn in the direction of the skid and lock the brakes"], a: 1 },
      { q: "You can not take your road test in a vehicle with any obstructions or consoles between the driver and the examiner because:", o: ["examiner cannot reach the brakes","obstruction is illegal","console takes up too much space","examiner cannot observe your feet"], a: 0 },
      { q: "Effective July 1, 2004, motorist in New Jersey may not use a hand-held wireless telephone while driving except for the following instances:", o: ["Fire","Traffic accidents","Medical emergency","All of the above"], a: 3 },
      { q: "The order of colors on a traffic light hung top to bottom:", o: ["red, yellow, green","red, green, yellow","green, yellow, green","yellow, green, red"], a: 0 },
      { q: "High beam lights are used for:", o: ["city streets without lamps","signaling emergencies","foggy weather","open country driving"], a: 3 },
      { q: "How many passengers may accompany the holder of a validated GDL Special Learners Permit in the vehicle?", o: ["0","Any passengers from their shared residence plus 1 additional person","2","None of the above."], a: 1 },
      { q: "The holder of a Provisional Driver License, under 21 years of age, is permitted to have how many non-household members in the car?", o: ["3 or more","2","1","0"], a: 2 },
      { q: "You cannot park within how many feet of a crosswalk at an intersection?", o: ["25 feet","10 feet","20 feet","50 feet"], a: 0 },
      { q: "The holder of a validated GDL Student Learner's Permit must meet which of the following requirements to obtain a Provisional License:", o: ["Pass road test","Attain 17 years of age","6 month minimum of supervised driving","A, B and C"], a: 3 },
      { q: "When approaching a railroad crossing with flashing lights you must:", o: ["stop at the crossing","slow down and look both ways","slow down, blow your horn and proceed with caution","all of the above"], a: 0 },
      { q: "When making a left turn from a two-way road, you should get close to the:", o: ["line nearest to the center of the road","left lane nearest to the left curb","right lane, or the lane furthest from the center lane","right lane, or the lane nearest to the right curb"], a: 0 },
      { q: "The holder of a Provisional Driver License is not permitted use of which of the following while driving:", o: ["Hand held electronic devices","Hand held video game","Cell phones","All of the above"], a: 3 },
      { q: "How much is the fine for violation of any of the conditions of the GDL Permits or Provisional License?", o: ["No fine.","$500.00","$100.00","$250.00"], a: 2 },
      { q: "The meaning of a hand signal when a driver's hand and arm are downward is:", o: ["Right-turn","U-turn","Left-turn","Slow or stop"], a: 3 },
      { q: "Whether your blood alcohol content rises above legal limits depends on:", o: ["amount you drink","your weight","time you take to drink","all of the above"], a: 3 },
      { q: "If not prohibited by a 'no turn on red sign', New Jersey law permits you to turn right on red after:", o: ["making a full stop and checking traffic","blowing your horn","slowing down to check traffic","checking traffic to your right"], a: 0 },
      { q: "Laws of New Jersey require you to keep to the right except:", o: ["when impractical to travel on that side of the roadway","when passing","when on a one-way street","all of the above"], a: 3 },
      { q: "Which of the following convictions will result in an Insurance Surcharge:", o: ["Operating Under the Influence of Liquor/Drugs","Operating Under the Influence of Liquor/Drugs and Refusal to Take a Breathalyzer Test","Refusal to Take a Breathalyzer Test","All of the above"], a: 3 },
      { q: "If you go into a skid you should:", o: ["straighten your wheels","make a fast turn","apply your brakes","take your foot off the gas pedal"], a: 3 },
      { q: "When sharing the road with large trucks or buses, you should:", o: ["Give more roadway to a truck making a wide turn.","Leave more space when stopping behind a truck or bus.","Maintain a consistent speed when passing.","All of the above."], a: 3 },
      { q: "A motorist will be subject to the following for a conviction of a 3rd violation of Operation Under the Influence of Liquor/Drugs:", o: ["Installation of interlock device OR suspension of all vehicle registrations","Installation of interlock device AND suspension of all vehicle registrations","Suspension of driving privilege","A and C"], a: 2 },
      { q: "Before turning, you must signal at least:", o: ["500 feet in advance","100 feet in advance","100 yards in advance","1 block in advance"], a: 1 },
      { q: "The holder of a validated GDL Examination Permit (21 years of age or older) is required to drive with supervision for a:", o: ["Minimum of 3 months","No supervision is required","Minimum of 9 months","Minimum of 6 months"], a: 0 },
      { q: "Emotions can have a great effect on your driving; if you are angry or excited you should:", o: ["give yourself time to cool off","blow your horn to warn other drivers","drive with your radio on","none of the above"], a: 0 },
      { q: "The holder of a validated GDL Special Learner's permit must not drive between the hours of:", o: ["12:01 AM and 5:00 AM","11:01 PM and 5:00 AM","11:01 PM and 6:00 AM","No restrictions apply"], a: 1 }
    ]
  },
  {
    id: 2,
    title: "Exam #2",
    questions: [
      { q: "A triangular shaped sign is a:", o: ["yield sign","warning sign","railroad sign","stop sign"], a: 0 },
      { q: "A holder of a student permit must have the following with them while driving:", o: ["Adult supervising driver in the front Seat","Their student permit","Registration and insurance ID card","All of the above"], a: 3 },
      { q: "Effective July 1, 2004, motorists in New Jersey may not use a hand-held wireless telephone while driving except for the following instances:", o: ["Fire","Traffic accidents","Medical emergency","All of the above"], a: 3 },
      { q: "When approaching or nearing an uncontrolled intersection you should:", o: ["speed up to clear intersection quickly","slow down and look straight ahead","reduce speed and be ready to stop","always come to a full stop"], a: 2 },
      { q: "When the pavement is marked with 2 centerlines, 1 solid and 1 broken:", o: ["passing is permitted only on the side with the broken line","passing is permitted on either side","passing is permitted on both sides, but only when the road is clear","passing is not permitted on either side"], a: 0 },
      { q: "Road surfaces are most slippery:", o: ["during very hot, humid weather","during very cold, dry weather","after a very heavy rainfall","during the first few minutes of a rainfall"], a: 3 },
      { q: "New Jersey law allows up to 3 points to be subtracted from your driving record if you have no moving traffic violation:", o: ["for 2 years from the date of the last violation","for 6 months from the date of the last violation","for 1 year from the date of the last violation","for 18 months from the date of the last violation"], a: 2 },
      { q: "If the driver of a large truck or bus cannot see you in his rearview mirrors, you are:", o: ["in the truck's no-zone or blind spot","Driving too slowly","Uninteresting to him","driving a compact car"], a: 0 },
      { q: "A single, solid white line across a road at an intersection means", o: ["no parking zone","bus stop","no passing","stop behind the line for a traffic sign or light"], a: 3 },
      { q: "The best way to take a curve is:", o: ["speed up while in the curve","lean in the direction of the curve","slow down before entering the curve","slow down after entering the curve"], a: 2 },
      { q: "When nearing a steady yellow or amber traffic signal, you should", o: ["stop immediately, do not continue through the intersection","slow down and continue with caution through the intersection","stop before entering the intersection, if you can safely do so","speed up and continue through the intersection before the light changes to red"], a: 2 },
      { q: "A twelve-ounce can of beer has as much alcohol in it as:", o: ["a bottle of rum","2 martinis","1½ ounces of 86 proof whiskey","a pint of brandy"], a: 2 },
      { q: "When approaching a railroad crossing with flashing lights you must:", o: ["stop at the crossing","slow down and look both ways","slow down, blow your horn and proceed with caution","all of the above"], a: 0 },
      { q: "To safely share the road with large trucks and buses, you must know:", o: ["The horsepower rating of your vehicle.","The history of the trucking industry.","Limitations of these vehicles regarding visibility, stopping distances required and maneuverability.","The impact trucks and large vehicles have on the environment."], a: 2 },
      { q: "Getting a drivers license illegally may result in:", o: ["imprisonment of 6 months","a fine of $200 to $500 and/or imprisonment of 30-90 days","a court trial","a fine of $25 to $100"], a: 1 },
      { q: "In adverse weather conditions, a truck takes longer to stop. This can be as much as:", o: ["70% more","25% more","50% more","100% more"], a: 1 },
      { q: "If under 21, New Jersey law states that you may be under the influence if your blood alcohol level content is", o: ["More than .10% but less than .15%","More than .05% but less than .10%","More than .01% but less than .05%","All of the above"], a: 3 },
      { q: "A supervising driver for the holder of a validated GDL Permit must meet which of the following requirements:", o: ["Must be 21 years or older","Must be a New Jersey licensed driver","Must be licensed for a minimum of 3 years","A, B, and C"], a: 3 },
      { q: "The holder of a validated GDL permit (21 years of age or older) is restricted to what driving hours?", o: ["6:01AM to midnight","No restrictions apply","5:01AM to midnight","5:01AM to 11:00PM"], a: 1 },
      { q: "The holder of a validated GDL Special Learner's permit must not drive between the hours of:", o: ["11:01PM and 6:00AM","11:01PM and 5:00AM","No restrictions apply","12:01AM and 5:00AM"], a: 1 },
      { q: "New Jersey law requires that a child must be seated in a child restraint device while riding in a car if:", o: ["the child is under 5 years of age and riding in the front seat","the child is under 18 months of age and is riding in the front seat","the child is under 18 months of age and is riding in the back seat","all of the above"], a: 3 },
      { q: "You may not park within how many feet of a fire hydrant?", o: ["50 feet","25 feet","20 feet","10 feet"], a: 3 },
      { q: "How many passengers may accompany the holder of a validated GDL Special Learners Permit in the vehicle?", o: ["0","Any passengers from their shared residence plus 1 additional person","2","None of the above."], a: 1 },
      { q: "In city driving, a good habit is to:", o: ["use the 2 second rule","reduce speed and use horn","look 12 seconds ahead","practice good judgment"], a: 2 },
      { q: "The '2 second rule' can be used at any speed to help you:", o: ["drive within the speed limit","bring your car out of a skid","time traffic lights at intersections","keep a safe following distance"], a: 3 },
      { q: "If you drink and have reached a BAC of slightly above .05%, the risk of your causing a motor vehicle accident is:", o: ["no different","triple","double","none of the above"], a: 2 },
      { q: "If you approach an intersection and a large truck is stopped for the traffic light, you should:", o: ["Blow your horn so the driver will know you are there.","Go around the truck on the right because he will startup slower.","Stop with enough distance so you will not be in a blind spot and you can see the driver in his mirror.","Stop as close to the rear of the truck as possible so no one can get in front of you."], a: 2 },
      { q: "When it is legal to turn right on red, before turning, you must:", o: ["slow down and check traffic","make a full stop and check traffic","blow your horn","check traffic to right"], a: 1 },
      { q: "If you drink beyond a BAC of .05%, the risk of your causing a motor vehicle accident doubles and at .10% the risk increases to:", o: ["4 times as great","10 times as great","6 times as great","3 times as great"], a: 2 },
      { q: "If a person has been drinking, which of the following can sober them up?", o: ["fresh air","drinking strong black coffee","time","a cold shower"], a: 2 },
      { q: "The best way to 'talk' to other drivers on the road is to:", o: ["be courteous and wave","use your horn and lights","roll down your window and yell","all of the above"], a: 1 },
      { q: "If you sell your car (and do not buy another) what should you do with the license plates?", o: ["give them to a friend to use","keep them as a souvenir","turn them into a Motor Vehicle inspection facility","throw them away"], a: 2 },
      { q: "In city driving you should:", o: ["drive more slowly","watch for pedestrians","look at least 12 seconds ahead","all of the above"], a: 3 },
      { q: "The holder of a Provisional Driver License is not permitted use of which of the following while driving:", o: ["Hand held electronic devices","Hand held video game","Cell phones","All of the above"], a: 3 },
      { q: "The holder of a Provisional License, who is under the age of 21, may drive unsupervised when the following requirement is met:", o: ["6 months of supervised driving","Pass a road test","Pass a road test after 6 months of supervised driving, excluding any suspensions or postponements","Pass a road test after 6 months of supervised driving"], a: 2 },
      { q: "You should always yield to:", o: ["emergency vehicles","pedestrians","other vehicles already in the intersection","all of the above"], a: 3 },
      { q: "In New Jersey, studded snow tires can be legally used between:", o: ["September 30th and May 30th","October 15th and March 15th","April 1st and December 15th","November 15th and April 1st"], a: 3 },
      { q: "When parking uphill on a street with a curb on your right, your car wheels should be:", o: ["turned away from the curb","turned straight ahead","turned to the right","turned toward the curb"], a: 0 },
      { q: "Altering a driver's license, or showing an altered driver's license, may result in", o: ["a fine of up to $1000","up to 6 months imprisonment","loss of your driving privilege","all of the above"], a: 3 },
      { q: "The driving hours of a GDL Examination Permit or Provisional License (under 21 years of age) are restricted to:", o: ["5:01AM to 11:00PM","5:01 AM to midnight","6:01 AM to midnight","No restrictions apply"], a: 1 },
      { q: "If a person gets drunk in your home and has a motor vehicle accident after leaving your home, you could:", o: ["be charged with a crime","not be held responsible","become involved in a lawsuit","none of the above"], a: 2 },
      { q: "A provisional driver is provisional for how long?", o: ["4 years","1 year","6 months","3 months"], a: 1 },
      { q: "When parking downhill on a street with a curb on your right, your car wheels should be:", o: ["turned away from the curb","turned straight ahead","turned toward the curb","turned to the left"], a: 2 },
      { q: "You cannot park:", o: ["in front of a fire hydrant","in a bus stop","in front of a driveway","all of the above"], a: 3 },
      { q: "Double solid lines in the center of a 2-way road means:", o: ["traffic should not cross from either side","'pass with care' road","a 1-way Street","a divided highway"], a: 0 },
      { q: "A person may operate a Moped with:", o: ["a valid basic license","a valid motorcycle license","a valid moped license","any of the above"], a: 3 },
      { q: "Emotions can have a great effect on your driving; if you are angry or excited you should:", o: ["give yourself time to cool off","blow your horn to warn other drivers","drive with your radio on","none of the above"], a: 0 },
      { q: "The best way to reduce your chances of having an alcohol related accident is to:", o: ["not drive at all after drinking","know your own limits","reduce your drinking","have a meal before drinking"], a: 0 },
      { q: "When making a left turn from a two-way road onto a 4 lane highway, the proper way to turn is:", o: ["approach the turn as close to the centerline of the road as possible","make the turn before reaching the center of the intersection","turn into the left lane of the road going in your direction","all of the above"], a: 3 },
      { q: "If you go into a skid you should:", o: ["take your foot off the gas pedal","straighten your wheels","apply your brakes","make a fast turn"], a: 0 }
    ]
  },
  {
    id: 3,
    title: "Exam #3",
    questions: [
      { q: "New Jersey law requires that a child must be seated in a child restraint device while riding in a car if:", o: ["the child is under 5 years of age and riding in the front seat","the child is under 18 months of age and is riding in the front seat","the child is under 18 months of age and is riding in the back seat","all of the above"], a: 3 },
      { q: "A Railroad Crossing Sign is:", o: ["Black and Red (Triangle)","White and Blue (Square)","Black and Yellow (Circle)","Green and White (Diamond)"], a: 2 },
      { q: "When sharing the road with large trucks or buses, you should:", o: ["Give more roadway to a truck making a wide turn.","Leave more space when stopping behind a truck or bus.","Maintain a consistent speed when passing.","All of the above."], a: 3 },
      { q: "If your wheels drift onto the dirt shoulder of the road and you want to return to the paved road, you should:", o: ["drive along the shoulder until you get to an acceleration lane","drive along the shoulder until you are going as fast as the traffic on the road","move slowly along shoulder and wave traffic around you","slow down, turn back onto the pavement slowly"], a: 3 },
      { q: "At the time of your Road Test, you must present", o: ["a valid vehicle registration","a valid examination permit","a valid insurance ID Card","all of the above"], a: 3 },
      { q: "A green light means:", o: ["be ready to stop","slow down","slow before an intersection","go when safe"], a: 3 },
      { q: "If you have a flat tire or blowout you should:", o: ["grip the wheel firmly","let up on the gas pedal","let car coast to a stop","all of the above"], a: 3 },
      { q: "You may not park within how many feet of a fire hydrant?", o: ["10 feet","50 feet","20 feet","25 feet"], a: 0 },
      { q: "Emotions can have a great effect on your driving; if you are angry or excited you should:", o: ["give yourself time to cool off","blow your horn to warn other drivers","drive with your radio on","none of the above"], a: 0 },
      { q: "When driving around a curve, your vehicle may tend to:", o: ["keep going straight","slow down","follow the curve","speed up"], a: 0 },
      { q: "When the pavement is marked with 2 centerlines, 1 solid and 1 broken:", o: ["passing is not permitted on either side","passing is permitted only on the side with the broken line","passing is permitted on either side","passing is permitted on both sides, but only when the road is clear"], a: 1 },
      { q: "When approaching a railroad crossing with flashing lights you must:", o: ["stop at the crossing","slow down and look both ways","slow down, blow your horn and proceed with caution","all of the above"], a: 0 },
      { q: "In adverse weather conditions, a truck takes longer to stop. This can be as much as:", o: ["70% more","100% more","25% more","50% more"], a: 2 },
      { q: "Dim your lights to low beam when:", o: ["driving on dark roads","parking on an unlit highway","entering a curve","a car is approaching you or when you are behind another car"], a: 3 },
      { q: "Any change of address must be reported to the Motor Vehicle Commission within what time period?", o: ["1 week","6 weeks","2 months","2 weeks"], a: 0 },
      { q: "To avoid highway hypnosis when driving on an expressway, it is a good practice to:", o: ["look straight ahead to the side","spend as much time looking at your mirrors as you do looking in front of you","rest your eyes by slowly blinking them from time to time","avoid looking at any one thing for more than a few seconds"], a: 3 },
      { q: "Hydroplaning is a driving condition wherein tires lose traction on a wet road and float on a layer of water or slush; when this happens, you should", o: ["push the brake pedal down hard","increase speed","change lanes","slow down"], a: 3 },
      { q: "A person may operate a Moped with:", o: ["a valid basic license","a valid motorcycle license","a valid moped license","any of the above"], a: 3 },
      { q: "The holder of a validated GDL Special Learner's permit must not drive between the hours of:", o: ["No restrictions apply","12:01 AM and 5:00 AM","11:01 PM and 5:00 AM","11:01 PM and 6:00 AM"], a: 2 },
      { q: "If under 21, New Jersey law states that you may be under the influence if your blood alcohol level content is", o: ["More than .10% but less than .15%","More than .05% but less than .10%","More than .01% but less than .05%","All of the above"], a: 3 },
      { q: "A twelve-ounce can of beer has as much alcohol in it as:", o: ["a pint of brandy","2 martinis","1½ ounces of 86 proof whiskey","a bottle of rum"], a: 2 },
      { q: "When you move into New Jersey from another state, you must have your vehicle inspected within:", o: ["90 days after registering it","2 months after registering it","6 months after registering it","14 days after registering it"], a: 3 },
      { q: "Police cars, fire trucks, ambulances, volunteer fire and rescue squad members responding to emergencies use sirens and red or blue flashing lights. When you see or hear them, you must:", o: ["speed up and stay at least 100 feet ahead of them","slow up and let them pass you","pull over to the extreme right of roadway and stop, letting them pass you","follow them and offer assistance"], a: 2 },
      { q: "You can reduce your chances of being involved in an accident by knowing and using the standard accident prevention formula:", o: ["be alert","be prepared","act in time","all of the above"], a: 3 },
      { q: "The holder of a validated GDL Student Learner's Permit must meet which of the following requirements to obtain a Provisional License:", o: ["Pass road test","Attain 17 years of age","6 month minimum of supervised driving","A, B and C"], a: 3 },
      { q: "The speed limit in a school zone, unless otherwise posted, is:", o: ["25 m.p.h.","15 m.p.h.","10 m.p.h.","35 m.p.h."], a: 0 },
      { q: "The holder of a validated GDL Examination Permit (21 years of age or older) is required to drive with supervision for a:", o: ["Minimum of 6 months","Minimum of 9 months","Minimum of 3 months","No supervision is required"], a: 2 },
      { q: "New Jersey law states that if you are 21 or over you may or may not be under the influence if your blood alcohol content is:", o: ["more than .10% but less than .15%","more than .15% but less than .20%","more than .05% but less than .08%","all of the above"], a: 2 },
      { q: "The shape of a yield sign is:", o: ["circle in square","triangle","eight-sided","diamond"], a: 1 },
      { q: "The holder of a Provisional License, who is under the age of 21, may drive unsupervised when the following requirement is met:", o: ["Pass a road test after 6 months of supervised driving","6 months of supervised driving","Pass a road test after 6 months of supervised driving, excluding any suspensions or postponements","Pass a road test"], a: 2 },
      { q: "Signals should be used:", o: ["when changing lanes","when turning","when slowing down","all of the above"], a: 3 },
      { q: "The driving hours of a GDL Examination Permit or Provisional License (under 21 years of age) are restricted to:", o: ["No restrictions apply","5:01AM to 11:00 PM","6:01 AM to midnight","5:01 AM to midnight"], a: 3 },
      { q: "On a two-lane road not near a school when a school bus is stopped and its red lights are flashing:", o: ["you must stop","you may pass the bus with caution","you may pass the bus from either direction","you may pass the bus at a speed of 10 mph. or less"], a: 0 },
      { q: "If a person has been drinking, which of the following can sober them up?", o: ["a cold shower","time","drinking strong black coffee","fresh air"], a: 1 },
      { q: "A supervising driver for the holder of a validated GDL Permit must meet which of the following requirements:", o: ["Must be 21 years or older","Must be a New Jersey licensed driver","Must be licensed for a minimum of 3 years","A, B, and C"], a: 3 },
      { q: "To safely share the road with large trucks and buses, you must know:", o: ["Limitations of these vehicles regarding visibility, stopping distances required and maneuverability.","The history of the trucking industry.","The horsepower rating of your vehicle.","The impact trucks and large vehicles have on the environment."], a: 0 },
      { q: "If you have a tire blowout:", o: ["apply your brakes","continue at regular speed until it is safe to slow down","slow down gradually","turn off the road quickly"], a: 2 },
      { q: "Laws of New Jersey require you to keep to the right except:", o: ["when impractical to travel on that side of the roadway","when passing","when on a one-way street","all of the above"], a: 3 },
      { q: "At what age is the holder of a GDL Special Learner's Permit eligible to obtain a basic driver license?", o: ["17, with passing the road test","18","18, with completion of Provisional requirements","17, with one year of supervised driving and passing the road test"], a: 2 },
      { q: "A provisional driver, during daylight hours when raining, must have", o: ["Wipers on","Headlights on","Both A & B","Defrosters only"], a: 2 },
      { q: "Altering a driver's license, or showing an altered driver's license, may result in", o: ["a fine of up to $1,000","up to 6 months imprisonment","loss of your driving privilege","all of the above"], a: 3 },
      { q: "A diamond shaped sign is a:", o: ["yield sign","stop sign","warning sign","railroad sign"], a: 2 },
      { q: "If you drink and have reached a BAC of slightly above .05%, the risk of your causing a motor vehicle accident is:", o: ["no different","triple","double","none of the above"], a: 2 },
      { q: "When parking downhill on a street with a curb on your right, your car wheels should be:", o: ["turned to the left","turned straight ahead","turned toward the curb","turned away from the curb"], a: 2 },
      { q: "A deceleration lane is:", o: ["the passing lane","an extra lane at a highway exit","for slow drivers only","for fast drivers only"], a: 1 },
      { q: "If a person gets drunk in your home and has a motor vehicle accident after leaving your home, you could:", o: ["be charged with a crime","not be held responsible","become involved in a lawsuit","none of the above"], a: 2 },
      { q: "The holder of a Provisional Driver License is not permitted use of which of the following while driving:", o: ["Hand held electronic devices","Hand held video game","Cell phones","All of the above"], a: 3 },
      { q: "The best way to 'talk' to other drivers on the road is to:", o: ["be courteous and wave","use your horn and lights","roll down your window and yell","all of the above"], a: 1 },
      { q: "If you approach an intersection and a large truck is stopped for the traffic light, you should:", o: ["Go around the truck on the right because he will start up slower.","Stop as close to the rear of the truck as possible so no one can get in front of you.","Blow your horn so the driver will know you are there.","Stop with enough distance so you will not be in a blind spot and you can see the driver in his mirror."], a: 3 },
      { q: "The best way to reduce your chances of having an alcohol related accident is to:", o: ["not drive at all after drinking","reduce your drinking","know your own limits","have a meal before drinking"], a: 0 }
    ]
  },
  {
    id: 4,
    title: "Exam #4",
    questions: [
      { q: "You should always yield to:", o: ["emergency vehicles","pedestrians","other vehicles already in the intersection","all of the above"], a: 3 },
      { q: "An eight-sided sign means:", o: ["yield to other traffic","stop","slow down","railroad crossing"], a: 1 },
      { q: "The speed limit in a school zone, unless otherwise posted, is:", o: ["25 m.p.h.","10 m.p.h.","15 m.p.h.","35 m.p.h."], a: 0 },
      { q: "The meaning of a hand signal when a driver's hand and arm are downward is:", o: ["U-turn","Left-turn","Right-turn","Slow or stop"], a: 3 },
      { q: "If you miss your exit on an expressway you should:", o: ["go on to the next exit","slow down and stop","turn around and go back","pull off the road and back up the shoulder"], a: 0 },
      { q: "When driving around a curve, your vehicle may tend to:", o: ["speed up","follow the curve","slow down","keep going straight"], a: 3 },
      { q: "If you approach an intersection and a large truck is stopped for the traffic light, you should:", o: ["Go around the truck on the right because he will start up slower.","Blow your horn so the driver will know you are there.","Stop as close to the rear of the truck as possible so no one can get in front of you.","Stop with enough distance so you will not be in a blind spot and you can see the driver in his mirror."], a: 3 },
      { q: "The driving hours of a GDL Examination Permit or Provisional License (under 21 years of age) are restricted to:", o: ["5:01AM to 11:00PM","5:01 AM to midnight","No restrictions apply","6:01 AM to midnight"], a: 1 },
      { q: "A single, solid white line across a road at an intersection means", o: ["stop behind the line for a traffic sign or light","no parking zone","bus stop","no passing"], a: 0 },
      { q: "It is a good practice to keep a space cushion to:", o: ["give you time to react","give you a clear view of the road","decrease your reaction time","none of the above"], a: 0 },
      { q: "When driving at night, be sure that you can stop:", o: ["within 20 feet at all times","within 20 feet at 30 miles per hour","within 20 feet at 40 miles per hour","within the distance you can see ahead"], a: 3 },
      { q: "To safely share the road with large trucks and buses, you must know:", o: ["The impact trucks and large vehicles have on the environment.","The history of the trucking industry.","Limitations of these vehicles regarding visibility, stopping distances required and maneuverability.","The horsepower rating of your vehicle."], a: 2 },
      { q: "Effective July 1, 2004, motorist in New Jersey may not use a hand-held wireless telephone while driving except for the following instances:", o: ["Fire","Traffic accidents","Medical emergency","All of the above"], a: 3 },
      { q: "When passing a large truck or bus, it is important to remember:", o: ["The name of the owner or business printed on the side of the truck.","There are several no-zones (blind spots) in which the driver cannot see you.","What the 'two-second' rule is.","All of the above."], a: 1 },
      { q: "A person may operate a Moped with:", o: ["a valid basic license","a valid motorcycle license","a valid moped license","any of the above"], a: 3 },
      { q: "The meaning of a hand-signal when a driver's hand and arm are upward is:", o: ["Left-Turn","Right-Turn","U-Turn","Slow-Stop"], a: 1 },
      { q: "If a person gets drunk in your home and has a motor vehicle accident after leaving your home, you could:", o: ["be charged with a crime","not be held responsible","become involved in a lawsuit","none of the above"], a: 2 },
      { q: "Before turning, you must signal at least:", o: ["1 block in advance","100 feet in advance","500 feet in advance","100 yards in advance"], a: 1 },
      { q: "When your license is returned to you after suspension for points (or after completing a DMV Driver Improvement Program), you will be on probation for:", o: ["two years","one year","6 months","9 months"], a: 1 },
      { q: "One and one-half ounces of 86 proof whiskey contains the same amount of alcohol as:", o: ["a 6-pack of beer","6 ounces of premium beer","a bottle of wine","12 ounces of beer"], a: 3 },
      { q: "New Jersey law requires that a child must be seated in a child restraint device while riding in a car if:", o: ["the child is under 5 years of age and riding in the front seat","the child is under 18 months of age and is riding in the front seat","the child is under 18 months of age and is riding in the back seat","all of the above"], a: 3 },
      { q: "To regain control while in a skid, you should:", o: ["make a fast turn in the direction of the skid and lock the brakes","turn in the opposite direction the back of the car is skidding","turn in the same direction the back of the car is skidding","keep a tight grip on the steering wheel"], a: 2 },
      { q: "Which of the following drinks contain the highest alcohol content?", o: ["5 ounces of table wine","1½ ounces of whiskey","12 ounces of beer","all of the above are about equal in content"], a: 3 },
      { q: "A provisional driver is provisional for how long?", o: ["1 year","3 months","4 years","6 months"], a: 0 },
      { q: "By law, you are under the influence when the amount of alcohol in your blood or BAC has reached:", o: [".01%",".05%",".08%","none of the above"], a: 2 },
      { q: "Under GDL Law, a person is required to attend a remedial training class for the following:", o: ["Accumulation of 4 or more points","Accumulation of 2 or more points","Conviction of a DUI","A and C"], a: 3 },
      { q: "Implied Consent Law means:", o: ["you must have liability insurance","you sign an agreement to give blood","permission for another to move your car in emergencies","when you drive a motor vehicle, you automatically agree to take a breath test following an arrest for a suspected drinking and driving offense"], a: 3 },
      { q: "When the pavement is marked with 2 centerlines, 1 solid and 1 broken:", o: ["passing is permitted on both sides, but only when the road is clear","passing is not permitted on either side","passing is permitted only on the side with the broken line","passing is permitted on either side"], a: 2 },
      { q: "Every vehicle registered in New Jersey must be insured for:", o: ["theft","fire damage","liability","collision"], a: 2 },
      { q: "You may pass on the right when:", o: ["the driver ahead is turning left and there is a proper lane on the right","there are no traffic signals","entering an intersection","there is a slow moving vehicle ahead"], a: 0 },
      { q: "The holder of a Provisional Driver License, under 21 years of age, is permitted to have how many non-household members in the car?", o: ["0","1","2","3 or more"], a: 1 },
      { q: "At the time of your Road Test, you must present", o: ["a valid vehicle registration","a valid examination permit","a valid insurance ID card","all of the above"], a: 3 },
      { q: "After two to four drinks, alcohol begins to impair your:", o: ["reaction time","coordination and balance","judgment","all of the above"], a: 3 },
      { q: "Any change of address must be reported to the Division of Motor Vehicle Services within what time period?", o: ["1 week","6 weeks","2 months","2 weeks"], a: 0 },
      { q: "To maintain a proper following distance when driving, you should stay at least:", o: ["3/4 of a second behind the vehicle in front of you","1/2 of a second behind the vehicle in front of you","2 seconds behind the vehicle in front of you","1 second behind the vehicle in front of you"], a: 2 },
      { q: "Which of the following convictions will result in an Insurance Surcharge:", o: ["Operating Under the Influence of Liquor/Drugs","Operating Under the Influence of Liquor/Drugs and Refusal to Take a Breathalyzer Test","Refusal to Take a Breathalyzer Test","All of the above"], a: 3 },
      { q: "When parking uphill on a street with a curb on your right, your car wheels should be:", o: ["turned away from the curb","turned toward the curb","turned to the right","turned straight ahead"], a: 0 },
      { q: "Road surfaces are most slippery:", o: ["after a very heavy rainfall","during the first few minutes of a rainfall","during very cold, dry weather","during very hot, humid weather"], a: 1 },
      { q: "If under 21, New Jersey law states that you may be under the influence if your blood alcohol level content is", o: ["More than .10% but less than .15%","More than .05% but less than .10%","More than .01% but less than .05%","All of the above"], a: 3 },
      { q: "When approaching a railroad crossing with flashing lights you must:", o: ["stop at the crossing","slow down and look both ways","slow down, blow your horn and proceed with caution","all of the above"], a: 0 },
      { q: "The holder of a validated GDL Student Learner's Permit must meet which of the following requirements to obtain a Provisional License:", o: ["Pass road test","Attain 17 years of age","6 month minimum of supervised driving","A, B and C"], a: 3 },
      { q: "You cannot park within how many feet of a crosswalk at an intersection?", o: ["50 feet","10 feet","25 feet","20 feet"], a: 2 },
      { q: "How much is the fine for violation of any of the conditions of the GDL Permits or Provisional License?", o: ["No fine.","$100.00","$500.00","$250.00"], a: 1 },
      { q: "When you move into New Jersey from another state, you must have your vehicle inspected within:", o: ["14 days after registering it","90 days after registering it","6 months after registering it","2 months after registering it"], a: 0 },
      { q: "High beam lights are used for:", o: ["signaling emergencies","open country driving","city streets without lamps","foggy weather"], a: 1 },
      { q: "If you go into a skid you should:", o: ["take your foot off the gas pedal","make a fast turn","straighten your wheels","apply your brakes"], a: 0 },
      { q: "A motorist will be subject to the following for a conviction of a 3rd violation of Operation Under the Influence of Liquor/Drugs:", o: ["Installation of interlock device OR suspension of all vehicle registrations","Installation of interlock device AND suspension of all vehicle registrations","Suspension of driving privilege","A and C"], a: 2 },
      { q: "The holder of a validated GDL Examination Permit (21 years of age or older) is required to drive with supervision for a:", o: ["Minimum of 3 months","Minimum of 6 months","No supervision is required","Minimum of 9 months"], a: 0 },
      { q: "If the driver of a large truck or bus cannot see you in his rearview mirrors, you are:", o: ["driving a compact car","Driving too slowly","Uninteresting to him","in the truck's no-zone or blind spot"], a: 3 },
      { q: "If a student driver commits a traffic offense, responsibility will be with:", o: ["neither student nor instructor","only the student","only the instructor","both student and instructor"], a: 3 }
    ]
  }
];
